### ISSUE TITLE
default import fails with Preact WMR

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/typography#2]
My current workaround:
```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import typography from '@twind/typography/module/twind_typography.js';
```

**Comment by sastan** [comment]
Thanks for the report. I fixed the published package. No other changes. Could you try 0.0.2. 

I'm going to re-write this like the other plugins. If you have any issues or wishes please let me know.

**Comment by danielweck** [comment]
Fixed, thank you :)
